name: React CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # or your preferred Node.js version

    - name: Install dependencies
      run: npm ci

#    - name: Run tests
   #   run: npm test

    - name: Build
      run: npm run build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/react-polycrome
          git pull origin main
          npm ci
          npm run build
          rm -rf /var/www/html/*
          cp -r build/* /var/www/html/
          sudo systemctl restart nginx
